// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKr6ZX6yxCL0QYk9w1FWLOUKk3k7aIwgU',
    appId: '1:657078459688:web:fb5d7b1c651f560b18041d',
    messagingSenderId: '657078459688',
    projectId: 'evateverywhere777',
    authDomain: 'evateverywhere777.firebaseapp.com',
    storageBucket: 'evateverywhere777.appspot.com',
    databaseURL: "https://evateverywhere777-default-rtdb.asia-southeast1.firebasedatabase.app",
    measurementId: "G-BYWV9BVBYW",
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyCHPN8BYv-GjpLd9EQqrbhyGqD8qRcd9B4',
      appId: '1:657078459688:android:64e28e315af4e3fc18041d',
      messagingSenderId: '657078459688',
      projectId: 'evateverywhere777',
      storageBucket: 'evateverywhere777.appspot.com',
      databaseURL: 'https://evateverywhere777-default-rtdb.asia-southeast1.firebasedatabase.app'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnEeYUOBPzyFLgbMkiFzPerVU2NqwDT2E',
    appId: '1:657078459688:ios:e9cbbcd04019654518041d',
    messagingSenderId: '657078459688',
    projectId: 'evateverywhere777',
    storageBucket: 'evateverywhere777.appspot.com',
    databaseURL: 'https://evateverywhere777-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosClientId: '657078459688-d9993j3v9hm123qf5nnl2jepcjgtt7og.apps.googleusercontent.com',
    iosBundleId: 'com.onyxdatasystems.evateverywhere',
  );

}
